import type { Metadata } from "next";
import "./globals.css";
import HeaderClient from "./components/layout/HeaderClient";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <HeaderClient />
                {children}
            </body>
        </html>
    );
}
